name: Strepsuis_seq Docker build and CI test

on: 
  pull_request:
     branches:
       - main
     paths:
       - 'Dockerfile'
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker build
        run: docker build -t ${{ secrets.CSU_ACCOUNT_NUMBER }}.dkr.ecr.eu-west-1.amazonaws.com/gitrun-csu-1016:${{ github.head_ref }} .
      - name: ECR Login
        run: |
          sudo aws ecr get-login-password --region eu-west-1 | sudo docker login --username AWS --password-stdin ${{ secrets.CSU_ACCOUNT_NUMBER }}.dkr.ecr.eu-west-1.amazonaws.com
      #- name: ECR Tag
        #run: |
        #  sudo docker tag gitrun-csu-1016:latest ${{ secrets.CSU_ACCOUNT_NUMBER }}.dkr.ecr.eu-west-1.amazonaws.com/gitrun-csu-1016:latest
      - name: ECR Push
        run: |
          sudo docker push ${{ secrets.CSU_ACCOUNT_NUMBER }}.dkr.ecr.eu-west-1.amazonaws.com/gitrun-csu-1016:${{ github.head_ref }}

  CI_testing:
    runs-on: ubuntu:latest
    # add someting to only run after build is complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Nextflow latest
        uses: nf-core/setup-nextflow@v1
        with:
          version: 'latest'

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run Tests
        run: nf-test test --ci
        